verson: 2
jobs: 
  build: 
    working_directrory: ~/backend
    docker: 
      - images: circleci/node:8.10
    steps: 
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run
        name: Install npm dependencies
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths: node_modules

    test:
      docker: 
        - images: circleci/node:8.10
      steps: 
      steps:
      - checkout
      - run:
          name: Test
          command: npm run test

  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Deploy
          command: bash ./scripts/deploy.sh my.awesome.website

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master

